name: Publish to npm

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
        env:
          SUPERSTORE_API_KEY: ${{ secrets.SUPERSTORE_API_KEY }}

      - name: Build package
        run: npm run build

      - name: Ensure release tag matches package version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF_NAME#v}
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Tag $GITHUB_REF_NAME does not match package version $PACKAGE_VERSION" >&2
            exit 1
          fi

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
