name: CI and Publish on Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm test
        env:
          SUPERSTORE_API_KEY: ${{ secrets.SUPERSTORE_API_KEY }}

      - name: Build package
        run: npm run build

      - name: Check if version already published
        id: version
        shell: bash
        run: |
          set -euo pipefail
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          echo "package_name=$NAME" >> $GITHUB_OUTPUT
          echo "package_version=$VERSION" >> $GITHUB_OUTPUT
          echo "Checking if $NAME@$VERSION exists on npm..."
          if npm view "$NAME@$VERSION" version >/dev/null 2>&1; then
            echo "already=true" >> $GITHUB_OUTPUT
            echo "Version already published; skipping publish."
          else
            echo "already=false" >> $GITHUB_OUTPUT
            echo "Version not published; will publish."
          fi

      - name: Publish to npm
        if: steps.version.outputs.already == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
